# Generated by Django 5.0.1 on 2024-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='цена урока'),
        ),
    ]
