# Generated by Django 4.2.9 on 2024-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False, 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
